site_name: Problem Solving Notes

repo_name: arnold518/ps-notes

repo_url: https://github.com/arnold518/ps-notes

theme:
  name: material
  features:
    - content.code.copy
    - navigation.sections
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.indexes
  icon:
    repo: fontawesome/brands/github
  language: ko  
  font:
    text: Noto Sans
    code: Ubuntu Mono
  palette: 
      - primary: deep purple
      - accent: deep purple
      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/weather-night
          name: Switch to light mode
    


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags:
      tags_file: tags.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/arnold518
  generator: false

copyright: Copyright &copy; 2023 - 2023 Jaemin Park

nav:
  - Home: index.md
  - 문제 풀이:
      - solutions/index.md
      - Olympiad:
          - IOI: a.md
          - KOISC: a.md
          - JOI: a.md
          - JOISC: a.md
          - JOIOC: a.md
          - APIO:
              - 2019:
                  - a.md
          - POI: a.md
          - KOI: a.md
      - BOJ:
          a.md
      - Codeforces:
          a.md
      - Atcoder:
          a.md
  - 알고리즘 & 자료구조 정리:
      - algorithms/index.md
  - 아이디어 & 테크닉 모음:
      - techniques/index.md
  - Tags: tags.md
