site_name: Problem Solving Notes

repo_name: arnold518/ps-notes

repo_url: https://github.com/arnold518/ps-notes

theme:
  name: material
  features:
    - content.code.copy
    - navigation.sections
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.indexes
    - navigation.expand
  icon:
    repo: fontawesome/brands/github
  language: ko  
  font:
    text: Noto Sans KR
    code: Ubuntu Mono
  palette: 
      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: deep purple
        accent: deep purple
        toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: deep purple
        accent: deep purple
        toggle:
          icon: material/weather-night
          name: Switch to light mode
    
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css


plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags:
      tags_file: tags.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/arnold518
  generator: false
  analytics:
    provider: google
    property: G-L0MHM11ZXZ

copyright: Copyright &copy; 2023 - 2023 Jaemin Park

nav:
  - Home: index.md
  - 문제 풀이:
      - solutions/index.md
      - Olympiad:
          - IOI:
              - 2022:
                  - Day 1:
                      - P1 Catfish Farm : solutions/Olympiad/IOI/2022/Day 1/P1 Catfish Farm/solution.md
                      - P2 Prisoner Challenge : solutions/Olympiad/IOI/2022/Day 1/P2 Prisoner Challenge/solution.md
              - 2019:
                  - Day 1:
                      - P1 Arranging Shoes : solutions/Olympiad/IOI/2019/Day 1/P1 Arranging Shoes/solution.md
                      - P2 Split the Attractions : solutions/Olympiad/IOI/2019/Day 1/P2 Split the Attractions/solution.md
                      - P3 Rectangles : solutions/Olympiad/IOI/2019/Day 1/P3 Rectangles/solution.md
          - KOISC: a.md
          - JOI: a.md
          - JOISC:
              - 2023:
                  - P1.1 Two Currencies : solutions/Olympiad/JOISC/2023/P1.1 Two Currencies/solution.md
                  - P1.3 Passport : solutions/Olympiad/JOISC/2023/P1.3 Passport/solution.md
          - JOIOC: a.md
          - APIO:
              - 2019:
                  - P1 Strange Device : solutions/Olympiad/APIO/2019/P1 Strange Device/solution.md
              - 2015:
                  - P1 Bali Sculptures : solutions/Olympiad/APIO/2015/P1 Bali Sculptures/solution.md
                  - P2 Jakarta Skyscrapers : solutions/Olympiad/APIO/2015/P2 Jakarta Skyscrapers/solution.md
          - POI: a.md
          - KOI: a.md
      - BOJ:
          - 28304 : solutions/BOJ/28304/solution.md
      - Codeforces:
          a.md
      - Atcoder:
          a.md
  - 알고리즘 & 자료구조 정리:
      - algorithms/index.md
      - Graphs:
          - Flows : 
              - Ford–Fulkerson method : algorithms/Graphs/Flows/Ford-Fulkerson method/algorithm.md
              - Edmond-Karp algorithm : algorithms/Graphs/Flows/Edmond-Karp algorithm/algorithm.md
              - Min Cost Max Flow : algorithms/Graphs/Flows/Min Cost Max Flow/algorithm.md
          - Theorems :
              - Kőnig's theorem : algorithms/Graphs/Theorems/Kőnig's theorem/algorithm.md
      - Strings:
          - Prefix Function : algorithms/Strings/Prefix Function/algorithm.md
          - KMP : algorithms/Strings/KMP/algorithm.md
          - Aho-Corasick : algorithms/Strings/Aho-Corasick/algorithm.md
          - Z Function : algorithms/Strings/Z Function/algorithm.md
          - Suffix Array & LCP Array : algorithms/Strings/Suffix Array & LCP Array/algorithm.md
          - Suffix Automaton : algorithms/Strings/Suffix Automaton/algorithm.md
      - Math:
          - Polynomials and Series :
              - FFT : algorithms/Math/Polynomials and Series/FFT/algorithm.md
              - FWHT : algorithms/Math/Polynomials and Series/FWHT/algorithm.md
  - 아이디어 & 테크닉 모음:
      - ideas/index.md
      - SCC of Tournament Graph : ideas/SCC of Tournament Graph/idea.md
  - Study:
      - study/index.md
      - Random Platinum Defence: study/Random Platinum Defence/rpd.md
      - Practice :
          - UCPC 2023 예선 : study/Practice/UCPC 2023 예선/post.md
          - SCPC 2023 Round 1 : study/Practice/SCPC 2023 Round 1/post.md
  - Tags: tags.md
